- name: start orion service
  k8s:
    state: present
    namespace: default
    src: "{{ root_dir }}/orion/orion-{{ ansible_play_name }}-service.yaml"

- name: check orion service
  k8s_info:
    kind: Service
    name: orion
    namespace: default
    label_selectors:
      - app = orion
  register: orion_service_result
  until: orion_service_result.resources | length == 1
  retries: 6
  delay: 10

- name: start orion deployment
  k8s:
    state: present
    namespace: default
    definition: "{{ lookup('template', '{{ root_dir }}/orion/orion-deployment.yaml.j2') }}"

- name: check oion deployment
  k8s_info:
    kind: Deployment
    name: orion
    namespace: default
  register: orion_deployment_result
  until:
    - orion_deployment_result.resources | length == 1
    - orion_deployment_result.resources[0].status is defined
    - orion_deployment_result.resources[0].status.readyReplicas is defined
    - orion_deployment_result.resources[0].status.readyReplicas == containers.orion.replicas
  retries: 45
  delay: 10

- name: check orion pods
  k8s_info:
    kind: Pod
    namespace: default
    label_selectors:
      - app = orion
  register: orion_pods_result
  until:
    - orion_pods_result.resources | length == containers.orion.replicas
    - orion_pods_result.resources | json_query('[?status.phase==`Running`]') | length == containers.orion.replicas
    - orion_pods_result.resources | json_query('[?status.containerStatuses[0].ready]') | length == containers.orion.replicas

- name: call orion REST API (ambassador returns 401 when the authorization header is not set)
  uri:
    url: "{{ base_url }}/orion/v2/entities/"
    method: GET
    status_code: 401
  register: orion_get_entities_no_auth_result

- name: call orion REST API (ambassador returns 200 when the valid authorization header is set)
  uri:
    url: "{{ base_url }}/orion/v2/entities/"
    headers:
      Authorization: "bearer {{ api_token }}"
    method: GET
    status_code: 200
  register: orion_get_entities_valid_auth_result
  until:
    - orion_get_entities_valid_auth_result.json == []
  retries: 45
  delay: 10
  vars:
    api_token: "{{ lookup('file', '{{ root_dir }}/secrets/auth-tokens.json') | from_json | json_query('[0].settings.bearer_tokens[0].token') }}"
