- name: start cygnus-mongo service
  k8s:
    state: present
    namespace: default
    src: "{{ root_dir }}/cygnus/cygnus-mongo-service.yaml"

- name: check cygnus-mongo service
  k8s_info:
    kind: Service
    name: cygnus-mongo
    namespace: default
    label_selectors:
      - app = cygnus-mongo
  register: cygnus_mongo_service_result
  until: cygnus_mongo_service_result.resources | length == 1
  retries: 6
  delay: 10

- name: start cygnus-mongo deployment
  k8s:
    state: present
    namespace: default
    definition: "{{ lookup('template', '{{ root_dir }}/cygnus/cygnus-mongo-deployment.yaml.j2') }}"

- name: check cygnus-mongo deployment
  k8s_info:
    kind: Deployment
    name: cygnus-mongo
    namespace: default
  register: cygnus_mongo_deployment_result
  until:
    - cygnus_mongo_deployment_result.resources | length == 1
    - cygnus_mongo_deployment_result.resources[0].status is defined
    - cygnus_mongo_deployment_result.resources[0].status.readyReplicas is defined
    - cygnus_mongo_deployment_result.resources[0].status.readyReplicas == replicas.cygnus_mongo
  retries: 60
  delay: 10

- name: check cygnus_mongo pods
  k8s_info:
    kind: Pod
    namespace: default
    label_selectors:
      - app = cygnus-mongo
  register: cygnus_mongo_pods_result
  until:
    - cygnus_mongo_pods_result.resources | length == replicas.cygnus_mongo
    - cygnus_mongo_pods_result.resources | json_query('[?status.phase==`Running`]') | length == replicas.cygnus_mongo
    - cygnus_mongo_pods_result.resources | json_query('[?status.containerStatuses[0].ready]') | length == replicas.cygnus_mongo
  retries: 60
  delay: 10
