- import_tasks: _start_orion.yml

- import_tasks: _start_iotagent_json.yml
  when: containers.iotagent_json.is_provisioning

- import_tasks: _start_iotagent_ul.yml
  when: containers.iotagent_ul.is_provisioning
