apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotagent-ul
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iotagent-ul
  template:
    metadata:
      labels:
        app: iotagent-ul
    spec:
      containers:
      - name: iotagent-ul
        image: fiware/iotagent-ul:1.9.0
        command: ["pm2-runtime", "bin/iotagent-ul"]
        args: ["--", "rb-config-ul.js"]
        ports:
        - containerPort: 4041
          name: manage
        - containerPort: 7896
          name: http
        env:
        - name: IOTA_CB_NGSI_VERSION
          value: "${IOTAGENT_UL_NGSI_VERSION}"
        volumeMounts:
          - name: config-volume
            mountPath: "/opt/iotaul/rb-config-ul.js"
            subPath: "rb-config-ul.js"
      volumes:
        - name: config-volume
          secret:
            secretName: iotagent-ul-config
