apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotagent-json
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iotagent-json
  template:
    metadata:
      labels:
        app: iotagent-json
    spec:
      containers:
      - name: iotagent-json
        image: fiware/iotagent-json:1.10.0
        command: ["pm2-runtime", "bin/iotagent-json"]
        args: ["--", "rb-config-json.js"]
        ports:
        - containerPort: 4041
          name: manage
        - containerPort: 7896
          name: http
        env:
        - name: IOTA_CB_NGSI_VERSION
          value: "${IOTAGENT_UL_NGSI_VERSION}"
        volumeMounts:
          - name: config-volume
            mountPath: "/opt/iotajson/rb-config-json.js"
            subPath: "rb-config-json.js"
      volumes:
        - name: config-volume
          secret:
            secretName: iotagent-json-config
