apiVersion: v1
kind: Service
metadata:
  name: iotagent-ul
  labels:
    app: iotagent-ul
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  iotagent-ul-manage-mapping
      prefix: /idas/ul20/manage/
      service: http://iotagent-ul:4041
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  iotagent-ul-http-mapping
      prefix: /idas/ul20/data/
      service: http://iotagent-ul:7896
spec:
  type: ClusterIP
  selector:
    app: iotagent-ul
  ports:
  - port: 4041
    name: iotagent-ul-manage-binding
  - port: 7896
    name: iotagent-ul-http-binding
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: iotagent-ul
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iotagent-ul
  template:
    metadata:
      labels:
        app: iotagent-ul
    spec:
      containers:
      - name: iotagent-ul
        image: ${REPOSITORY}/tech-sketch/iotagent-ul:1.7.0.plus
        imagePullPolicy: Always
