apiVersion: v1
kind: Service
metadata:
  name: ambassador
  creationTimestamp: null
  labels:
    service: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
spec:
  type: LoadBalancer
  ports:
  - name: ambassador-tls
    port: 443
    targetPort: 443
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    service: ambassador
