apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    app: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: ambassador-tls
    port: 443
    targetPort: 8443
  - name: ambassador
    port: 80
    targetPort: 8080
  selector:
    app: ambassador
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  config:
    diagnostics:
      enabled: false
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: tls
spec:
  config:
    server:
      enabled: True
      redirect_cleartext_from: 8080
      secret: ambassador-certs
