apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    app: ambassador
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: ambassador
    port: 80
    targetPort: 8080
  selector:
    app: ambassador
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  config:
    diagnostics:
      enabled: false
