apiVersion: v1
kind: Service
metadata:
  name: ambassador
  creationTimestamp: null
  labels:
    app: ambassador
spec:
  type: NodePort
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    app: ambassador
