apiVersion: v1
kind: Service
metadata:
  name: bearer-auth
  labels:
    service: bearer-auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name:  authentication
      config:
        auth_service: "bearer-auth:3000"
spec:
  type: ClusterIP
  selector:
    pod: bearer-auth
  ports:
  - name: bearer-auth
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bearer-auth
spec:
  replicas: 3
  template:
    metadata:
      labels:
        pod: bearer-auth
    spec:
      containers:
      - name: bearer-auth-api
        image: fiwareacr.azurecr.io/tech-sketch/fiware-bearer-auth:0.1.0
        env:
        - name: LISTEN_PORT
          value: "3000"
        - name: AUTH_TOKENS
          valueFrom:
            secretKeyRef:
              name: "auth-tokens"
              key: "auth-tokens.json"
        ports:
          - name: bearer-auth
            containerPort: 3000

