apiVersion: v1
kind: Service
metadata:
  name: ambassador-auth
  labels:
    service: ambassador-auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name:  authentication
      config:
        auth_service: "ambassador-auth:3000"
spec:
  type: ClusterIP
  selector:
    pod: ambassador-auth
  ports:
  - name: ambassador-auth
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ambassador-auth
spec:
  replicas: 3
  template:
    metadata:
      labels:
        pod: ambassador-auth
    spec:
      containers:
      - name: ambassador-auth-api
        image: techsketch/fiware-ambassador-auth:0.1.1
        imagePullPolicy: Always
        env:
        - name: LISTEN_PORT
          value: "3000"
        - name: AUTH_TOKENS
          valueFrom:
            secretKeyRef:
              name: "auth-tokens"
              key: "auth-tokens.json"
        ports:
          - name: ambassador-auth
            containerPort: 3000
