apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orion
  template:
    metadata:
      labels:
        app: orion
    spec:
      containers:
      - name: orion
        image: fiware/orion:2.2.0
        args: ["-dbhost", "mongodb-client", "-rplSet", "rs0", "-dbTimeout", "10000", "-logLevel", "DEBUG"]
        ports:
        - containerPort: 1026
          name: orion
