apiVersion: v1
kind: Service
metadata:
  name: orion
  labels:
    app: orion
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  orion-mapping
      prefix: /orion/
      host: "^api\\..+$"
      host_regex: true
      service: http://orion:1026
spec:
  type: ClusterIP
  selector:
    app: orion
  ports:
  - port: 1026
    targetPort: orion
    name: orion
