apiVersion: v1
kind: Service
metadata:
  name: orion
  labels:
    app: orion
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  orion-mapping
      prefix: /orion/
      service: http://orion:1026
spec:
  type: ClusterIP
  selector:
    app: orion
  ports:
  - port: 1026
    targetPort: orion
    name: orion
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: orion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orion
  template:
    metadata:
      labels:
        app: orion
    spec:
      containers:
      - name: orion
        image: fiware/orion
        args: ["-dbhost", "mongodb", "-rplSet", "rs0", "-dbTimeout", "10000", "-logLevel", "DEBUG"]
        ports:
        - containerPort: 1026
          name: orion
