---
minikube:
  name: minikube_rb
  vm_driver: virtualbox

k8s:
  version: 1.17.0

docker:
  registry:
    version: 2.7.1
    name: registry
    port: 5000

nat:
  mqtt: 1883
  web_mqtt: 15675
  http: 8080

replicas:
  rabbitmq: 2
  mongodb: 2
  ambassador: 1
  auth: 1
  orion: 1
  iotagent_json: 1
  iotagent_ul: 1
  cygnus_mongo: 1
  sth_comet: 1
  cygnus_elasticsearch: 1
  ekf:
    elasticsearch:
      master: 2
      data: 2
      coordinating: 1
    kibana: 1
