apiVersion: v1
kind: Service
metadata:
  name: turtlebot3-fake
  labels:
    app: turtlebot3-fake
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: turtlebot3-fake
  ports:
  - port: 11311
    targetPort: 11311
