- name: retrieve host IP addr
  shell: |
    ifconfig {{ nwname }} | \
    awk '/inet / {print $2}'
  register: vbox_hostip_result
- name: set host IP
  set_fact:
    host_ipaddr: "{{ vbox_hostip_result.stdout }}"
- debug: var=host_ipaddr

- name: retrieve netmask
  shell: |
    ifconfig {{ nwname }} | \
    awk '/netmask / {print $4}' | \
    sed 's/^0x//g' | \
    perl -pe '$_ = unpack("B32", pack("H*", $_)); s/0+$//g; $_ = length'
  register: vbox_netmask_result
- name: set netmask
  set_fact:
    netmask: "{{ vbox_netmask_result.stdout }}"
- debug: var=netmask
