apiVersion: v1
kind: Service
metadata:
  name: turtlebot3-operator
  labels:
    app: turtlebot3-operator
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: turtlebot3-operator
  ports:
  - port: 11311
    targetPort: 11311
