apiVersion: v1
kind: ConfigMap
metadata:
  name: turtlebot3-operator-configmaps
  namespace: default
  labels:
    app: turtlebot3-operator
data:
  config.yaml: |
    bridge:
      topics:
        cmd_sub: "/turtlebot3_bridge/cmd"
        attrs_pub: "/turtlebot3_bridge/attrs"
      thresholds:
        send_delta_millisec: 200
    turtlebot3:
      rate_hz: 10
      circle:
        velocities:
          x: 0.1
          z: 0.4
        thresholds:
          dist_meter: 0.1
          angular_rad: 0.02
      polygon:
        velocities:
          x: 0.2
          z: 0.2
        edge:
          length_meter: 0.4
        thresholds:
          dist_meter: 0.01
          angular_rad: 0.02
      unit:
        length_meter: 0.1
        theta_rad: 0.17453292519
      topics:
        cmd_pub: "/cmd_vel"
        odom_sub: "/odom"
