apiVersion: v1
kind: Service
metadata:
  name: comet
  labels:
    app: comet
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  comet-mapping
      prefix: /comet/
      host_regex: true
      service: http://comet:8666
spec:
  type: ClusterIP
  selector:
    app: comet
  ports:
  - port: 8666
    targetPort: comet
    name: comet
