apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-master
  labels:
    app: ros-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-master
  template:
    metadata:
      labels:
        app: ros-master
    spec:
      containers:
      - name: ros-master
        image: "${EXTERNAL_HOST_IPADDR}:5000/tech-sketch/ros-master:0.2.0"
        imagePullPolicy: Always
        command:
        - "/opt/kube_entrypoint.sh"
        ports:
        - containerPort: 11311
        volumeMounts:
        - mountPath: "/usr"
          name: usr
          readOnly: true
        - mountPath: "/lib"
          name: lib
          readOnly: true
        - mountPath: "/lib64"
          name: lib64
          readOnly: true
        - mountPath: "/opt/ros"
          name: opt-ros
          readOnly: true
      volumes:
      - name: usr
        hostPath:
          path: "/usr"
          type: Directory
      - name: lib
        hostPath:
          path: "/lib"
          type: Directory
      - name: lib64
        hostPath:
          path: "/lib64"
          type: Directory
      - name: opt-ros
        hostPath:
          path: "/opt/ros"
          type: Directory
