apiVersion: v1
kind: Service
metadata:
  name: ros-master
  labels:
    app: ros-master
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: ros-master
  ports:
  - name: ros-port
    protocol: TCP
    port: 11311
    targetPort: 11311
