apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  AuthService
      name:  authentication
      auth_service: "auth:3000"
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - name: auth
    port: 3000
    targetPort: 3000
