apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: roboticbase/fiware-ambassador-auth:0.3.0
        imagePullPolicy: Always
        env:
        - name: LISTEN_PORT
          value: "3000"
        - name: AUTH_TOKENS_PATH
          value: "/opt/secrets/auth-tokens.json"
        volumeMounts:
        - name: auth-tokens-volume
          mountPath: "/opt/secrets/"
        ports:
          - name: auth
            containerPort: 3000
      volumes:
        - name: auth-tokens-volume
          secret:
            secretName: auth-tokens
