apiVersion: v1
kind: Service
metadata:
  name: cygnus-mongo
  labels:
    app: cygnus-mongo
spec:
  type: ClusterIP
  selector:
    app: cygnus-mongo
  ports:
  - port: 5050
    name: cygnus-mongo-service
  - port: 8081
    name: cygnus-mongo-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cygnus-mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cygnus-mongo
  template:
    metadata:
      labels:
        app: cygnus-mongo
    spec:
      containers:
      - name: cygnus-mongo
        image: techsketch/fiware-cygnus:1.9.0.elasticsearch
        imagePullPolicy: Always
        env:
        - name: CYGNUS_SERVICE_PORT
          value: "5050"
        - name: CYGNUS_API_PORT
          value: "8081"
        - name: CYGNUS_LOG_LEVEL
          value: "INFO"
        - name: CYGNUS_MONGO_HOSTS
          value: "mongodb:27017"
        - name: CYGNUS_MONGO_USER
          value: ""
        - name: CYGNUS_MONGO_PASS
          value: ""
        - name: CYGNUS_MONGO_ATTR_PERSISTENCE
          value: "column"
