apiVersion: v1
kind: Service
metadata:
  name: cygnus
  labels:
    app: cygnus
spec:
  type: ClusterIP
  selector:
    app: cygnus
  ports:
  - port: 5050
    name: cygnus-service
  - port: 8081
    name: cygnus-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cygnus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cygnus
  template:
    metadata:
      labels:
        app: cygnus
    spec:
      containers:
      - name: cygnus
        image: ${REPOSITORY}/tech-sketch/cygnus-ngsi:1.8.0
        imagePullPolicy: Always
        env:
        - name: CYGNUS_MONGO_HOSTS
          value: "mongodb:27017"
        - name: CYGNUS_MONGO_USER
          value: ""
        - name: CYGNUS_MONGO_PASS
          value: ""
