apiVersion: v1
kind: Service
metadata:
  name: cygnus
  labels:
    app: cygnus
spec:
  type: ClusterIP
  selector:
    app: cygnus
  ports:
  - port: 5050
    name: cygnus-service
  - port: 8081
    name: cygnus-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cygnus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cygnus
  template:
    metadata:
      labels:
        app: cygnus
    spec:
      containers:
      - name: cygnus
        image: techsketch/fiware-cygnus:1.9.0.elasticsearch
        imagePullPolicy: Always
        env:
        - name: CYGNUS_SERVICE_PORT
          value: "5050"
        - name: CYGNUS_API_PORT
          value: "8081"
        - name: CYGNUS_LOG_LEVEL
          value: "DEBUG"
        - name: CYGNUS_ELASTICSEARCH_HOST
          value: "elasticsearch-logging.monitoring.svc.cluster.local"
        - name: CYGNUS_ELASTICSEARCH_PORT
          value: "9200"
        - name: CYGNUS_ELASTICSEARCH_SSL
          value: "false"
