global:
  rbacEnable: true

alertmanager:
  image:
    repository: quay.io/prometheus/alertmanager
    tag: v0.16.1

prometheus:
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.7.1

grafana:
  image:
    repository: grafana/grafana
    tag: 5.4.3
  auth:
    anonymous:
      enabled: "false"

deployCoreDNS: true
deployKubeDNS: false
