global:
  rbacEnable: true

alertmanager:
  image:
    repository: quay.io/prometheus/alertmanager
    tag: v0.16.2

prometheus:
  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.9.1

grafana:
  image:
    repository: grafana/grafana
    tag: 6.1.4
  auth:
    anonymous:
      enabled: "false"

deployCoreDNS: true
deployKubeDNS: false
