alertmanager:
  alertmanagerSpec:
    image:
      repository: quay.io/prometheus/alertmanager
      tag: v0.17.0
    storage:
      volumeClaimTemplate:
        metadata:
          name: prometheus-alertmanager-storage-claim
          annotations:
            volume.beta.kubernetes.io/storage-class: managed-premium
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
        selector: {}

prometheus:
  prometheusSpec:
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.10.0
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-prometheus-storage-claim
          annotations:
            volume.beta.kubernetes.io/storage-class: managed-premium
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
        selector: {}

grafana:
  image:
    repository: grafana/grafana
    tag: 6.2.4
  auth:
    anonymous:
      enabled: "false"

prometheusOperator:
  configReloaderCpu: 400m

kubelet:
  serviceMonitor:
    https: false
