---
root_dir: "{{ inventory_dir }}/../../.."
envfile_path: "{{ inventory_dir  }}/../../../docs/environments/minikube/env"

containers:
  rabbitmq:
    replicas: 3
    image: rabbitmq:3.8.2
  mongodb:
    replicas: 3
    repository: mongo
    tag: 4.2.3
  ambassador:
    replicas: 3
    image: quay.io/datawire/ambassador:1.1.1
  auth:
    replicas: 3
    image: roboticbase/fiware-ambassador-auth:0.3.0

mqtt:
  users:
    - name: iotagent
      password: password_of_iotagent
