---
root_dir: "{{ inventory_dir }}/../../.."
envfile_path: "{{ inventory_dir  }}/../../../docs/environments/minikube/env"

containers:
  rabbitmq:
    replicas: 3
    image: rabbitmq:3.8.2
  mongodb:
    replicas: 3
    repository: mongo
    tag: 4.2.3
  ambassador:
    replicas: 3
    image: quay.io/datawire/ambassador:1.1.1
  auth:
    replicas: 3
    image: roboticbase/fiware-ambassador-auth:0.3.0
  orion:
    replicas: 3
    image: fiware/orion:2.3.0
  iotagent_json:
    is_provisioning: true
    replicas: 3
    image: fiware/iotagent-json:1.13.0
    cb_ngsi_version: v1
    autocast: true
  iotagent_ul:
    is_provisioning: true
    replicas: 3
    image: fiware/iotagent-ul:1.12.0
    cb_ngsi_version: v1
    autocast: true
  cygnus_mongo:
    is_provisioning: true
    replicas: 3
    image: fiware/cygnus-ngsi:1.17.1

mqtt:
  users:
    - name: iotagent
      password: password_of_iotagent
