- name: start cygnus-elasticsearch service
  k8s:
    state: present
    namespace: default
    src: "{{ root_dir }}/cygnus/cygnus-elasticsearch-service.yaml"

- name: check cygnus-elasticsearch service
  k8s_info:
    kind: Service
    name: cygnus-elasticsearch
    namespace: default
    label_selectors:
      - app = cygnus-elasticsearch
  register: cygnus_elasticsearch_service_result
  until: cygnus_elasticsearch_service_result.resources | length == 1
  retries: 6
  delay: 10

- name: start cygnus-elasticsearch deployment
  k8s:
    state: present
    namespace: default
    definition: "{{ lookup('template', '{{ root_dir }}/cygnus/cygnus-elasticsearch-deployment.yaml.j2') }}"

- name: check cygnus-elasticsearch deployment
  k8s_info:
    kind: Deployment
    name: cygnus-elasticsearch
    namespace: default
  register: cygnus_elasticsearch_deployment_result
  until:
    - cygnus_elasticsearch_deployment_result.resources | length == 1
    - cygnus_elasticsearch_deployment_result.resources[0].status is defined
    - cygnus_elasticsearch_deployment_result.resources[0].status.readyReplicas is defined
    - cygnus_elasticsearch_deployment_result.resources[0].status.readyReplicas == containers_extra.cygnus_elasticsearch.replicas
  retries: 60
  delay: 10

- name: check cygnus-elasticsearch pods
  k8s_info:
    kind: Pod
    namespace: default
    label_selectors:
      - app = cygnus-elasticsearch
  register: cygnus_elasticsearch_pods_result
  until:
    - cygnus_elasticsearch_pods_result.resources | length == containers_extra.cygnus_elasticsearch.replicas
    - cygnus_elasticsearch_pods_result.resources | json_query('[?status.phase==`Running`]') | length == containers_extra.cygnus_elasticsearch.replicas
    - cygnus_elasticsearch_pods_result.resources | json_query('[?status.containerStatuses[0].ready]') | length == containers_extra.cygnus_elasticsearch.replicas
  retries: 60
  delay: 10
