kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-amqp
  labels:
    app: rabbitmq
    service: amqp
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-mqtt
  labels:
    app: rabbitmq
    service: mqtt
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
   - name: mqtt
     protocol: TCP
     port: 1883
     targetPort: 1883
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-mqtts
  labels:
    app: rabbitmq
    service: mqtts
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
   - name: mqtts
     protocol: TCP
     port: 8883
     targetPort: 8883
