replicas: 3
port: 27017
fullnameOverride: mongodb

replicaSetName: rs0

auth:
  enabled: false

# Specs for the Docker image for the init container that establishes the replica set
installImage:
  repository: unguiculus/mongodb-install
  tag: 0.7
  pullPolicy: IfNotPresent

# Specs for the Docker image for the copyConfig init container
copyConfigImage:
  repository: busybox
  tag: 1.29.3
  pullPolicy: IfNotPresent

# Specs for the MongoDB image
image:
  repository: mongo
  tag: 4.1.13
  pullPolicy: IfNotPresent

# Prometheus Metrics Exporter
metrics:
  enabled: false
  image:
    repository: ssalaues/mongodb-exporter
    tag: 0.6.1
    pullPolicy: IfNotPresent
  port: 9216
  path: "/metrics"
  socketTimeout: 3s
  syncTimeout: 1m
  prometheusServiceDiscovery: true
  resources: {}

# Annotations to be added to MongoDB pods
podAnnotations: {}

resources: {}
# limits:
#   cpu: 500m
#   memory: 512Mi
# requests:
#   cpu: 100m
#   memory: 256Mi

persistentVolume:
  enabled: false

# Annotations to be added to the service
serviceAnnotations: {}

terminationGracePeriodSeconds: 30

# Entries for the MongoDB config file
configmap: {}
