apiVersion: batch/v1
kind: Job
metadata:
  name: simple-dump-job
  labels:
    job: simple-dump-job
spec:
  template:
    metadata:
      labels:
        job: simple-dump-job
    spec:
      containers:
      - name: simple-dump-job
        image: roboticbase/mongodb-simple-backup:0.1.0
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: TIMEZONE
          value: "Asia/Tokyo"
        - name: MONGODB_ENDPOINT
          value: "rs0/mongodb-0.mongodb:27017,mongodb-1.mongodb:27017,mongodb-2.mongodb:27017"
        - name: STORE_OPLOG
          value: "true"
        - name: DUMPFILE_PREFIX
          value: "mongodump_"
        - name: STORAGE_ACCOUNT
          value: "${STORAGE_ACCOUNT}"
        - name: ACCOUNT_KEY
          value: "${ACCOUNT_KEY}"
        - name: STORAGE_CONTAINER
          value: "${STORAGE_CONTAINER}"
      restartPolicy: Never
  backoffLimit: 3
