- name: start minikube
  command: |
    minikube start \
    --cpus {{ resources.cpu_core_num }} \
    --memory {{ resources.memory_mb }} \
    --kubernetes-version {{ k8s.version }} \
    --profile {{ minikube.name }} \
    --vm-driver {{ minikube.vm_driver }}
  register: minikube_start_result
  when: minikube_status.Host != "Running"

- debug: var=minikube_start_result.stdout_lines
  when: minikube_status.Host != "Running"

- name: check node status
  command: |
    kubectl get nodes
  register: k8s_node_status_result
  until: k8s_node_status_result.stdout | regex_replace('^.*\n\\S+\\s+(\\S+)\\s+.*$', '\\1') == "Ready"
  retries: 6
  delay: 10

- debug: var=k8s_node_status_result.stdout_lines
