- import_tasks: _clear_envfile.yml

- import_tasks: _check_minikube_status.yml
- import_tasks: _stop_minikube.yml
- import_tasks: _delete_minikube.yml

- import_tasks: _check_minikube_status.yml
- import_tasks: _start_minikube.yml

- import_tasks: _nw_configuration_of_common.yml
- include_tasks: _nw_configuration_of_{{ ansible_os_family }}_{{ ansible_distribution }}.yml
- import_tasks: _add_nw_configuration_to_envfile.yml

- import_tasks: _edit_configuration_of_minikube.yml

- import_tasks: _check_minikube_status.yml
- import_tasks: _stop_minikube.yml

- import_tasks: _check_minikube_status.yml
- import_tasks: _start_minikube.yml

- import_tasks: _start_local_registry.yml

- import_tasks: _setup_rbac.yml

- import_tasks: _setup_helm.yml
