apiVersion: v1
kind: Service
metadata:
  name: wirecloud
  labels:
    app: wirecloud
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  wirecloud-mapping
      prefix: /
      host: "^wirecloud\\..+$"
      host_regex: true
      service: http://wirecloud:8888
spec:
  type: ClusterIP
  selector:
    app: wirecloud
  ports:
  - port: 8888
    targetPort: wirecloud-nginx
    name: wirecloud
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wirecloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wirecloud
  template:
    metadata:
      labels:
        app: wirecloud
    spec:
      containers:
      - name: wirecloud-django
        image: fiware/wirecloud:1.2
        env:
        - name: DEBUG
          value: "False"
        - name: FORWARDED_ALLOW_IPS
          value: "*"
        ports:
        - containerPort: 8000
          name: wirecloud-app
        volumeMounts:
        - name: static-dir
          mountPath: /var/www/static
      - name: wirecloud-nginx
        image: nginx
        ports:
        - containerPort: 8888
          name: wirecloud-nginx
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: static-dir
          mountPath: /var/www/static
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: static-dir
        emptyDir: {}
