apiVersion: v1
kind: Service
metadata:
  name: sth
  labels:
    app: sth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  sth-mapping
      prefix: /sth/
      service: http://sth:8666
spec:
  type: ClusterIP
  selector:
    app: sth
  ports:
  - port: 8666
    targetPort: sth
    name: sth
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sth
  template:
    metadata:
      labels:
        app: sth
    spec:
      containers:
      - name: sth
        image: telefonicaiot/fiware-sth-comet:2.5.0
        env:
        - name: STH_HOST
          value: "0.0.0.0"
        - name: DB_URI
          value: "mongodb:27017"
        - name: REPLICA_SET
          value: "rs0"
        - name: LOGOPS_LEVEL
          value: "DEBUG"
        ports:
        - containerPort: 8666
          name: sth
