apiVersion: v1
kind: Service
metadata:
  name: robot-visualization
  labels:
    service: robot-visualization
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  visualizer-mapping
      prefix: /visualizer/
      service: http://robot-visualization:8888
spec:
  type: ClusterIP
  selector:
    pod: robot-visualization
  ports:
  - name: robot-vis
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: robot-visualization
spec:
  replicas: 3
  template:
    metadata:
      labels:
        pod: robot-visualization
    spec:
      containers:
      - name: fiware-robot-visualization
        image: techsketch/fiware-robot-visualization:0.1.1
        imagePullPolicy: Always
        env:
        - name: LISTEN_PORT
          value: "8888"
        - name: PREFIX
          value: "/visualizer"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: BEARER_AUTH
          value: "${BEARER_AUTH}"
        - name: MONGODB_ENDPOINT
          value: "mongodb:27017"
        - name: MONGODB_REPLICASET
          value: "rs0"
        - name: MONGODB_DATABASE
          value: "${MONGODB_DATABASE}"
        - name: MONGODB_COLLECTION
          value: "${MONGODB_COLLECTION}"
        ports:
          - name: robot-vis
            containerPort: 8888
