apiVersion: v1
kind: Service
metadata:
  name: cmd-proxy
  labels:
    service: cmd-proxy
spec:
  type: ClusterIP
  selector:
    pod: cmd-proxy
  ports:
  - name: cmd-proxy
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cmd-proxy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        pod: cmd-proxy
    spec:
      containers:
      - name: fiware-cmd-proxy
        image: fiwareacr.azurecr.io/tech-sketch/fiware-cmd-proxy:0.1.0
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        ports:
          - name: cmd-proxy
            containerPort: 8888
