- name: create auth-token secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: auth-tokens
        namespace: default
      data:
        auth-tokens.json: "{{ encoded_auth_tokens }}"
  vars:
    encoded_auth_tokens: "{{ lookup('file', '{{ root_dir }}/secrets/auth-tokens.json') | b64encode }}"

- name: check auth-token secret
  k8s_info:
    kind: Secret
    name: auth-tokens
    namespace: default
  register: auth_tokens_secret_result
  until: auth_tokens_secret_result.resources | length == 1
  retries: 6
  delay: 10
