- import_tasks: _check_existing_auth_token.yml

- include_tasks: _create_{{ ansible_play_name }}_auth_tokens.yml
  when: existing_auth_tokens_secret | int == 0
- import_tasks: _create_auth_token_secret.yml
  when: existing_auth_tokens_secret | int == 0

- import_tasks: _start_auth.yml
