- name: retrieve network name
  shell: |
    VBoxManage showvminfo {{ minikube.name }} | \
    grep "Host-only Interface" | \
    awk 'match($0, /vboxnet[0-9]+/){print substr($0,RSTART,RLENGTH)}'
  register: vbox_vminfo_result
- name: set nwname
  set_fact:
    nwname: "{{ vbox_vminfo_result.stdout }}"

- name: get host IP addr and netmask of minikube
  get_network_info:
    nwname: "{{ nwname }}"
  register: get_network_info_result
- name: set host_ipaddr
  set_fact:
    host_ipaddr: "{{ get_network_info_result.host_ipaddr }}"
- debug: var=host_ipaddr

- name: set netmask
  set_fact:
    netmask: "{{ get_network_info_result.netmask }}"
- debug: var=netmask
