apiVersion: v1
kind: Service
metadata:
  name: ros-bridge
  labels:
    app: ros-bridge
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: ros-bridge
  ports:
  - port: 11311
    targetPort: 11311
