- import_tasks: _create_namespace.yml
  when: containers.cygnus_elasticsearch.is_provisioning

- import_tasks: _start_cygnus_elasticsearch.yml
  when: containers.cygnus_elasticsearch.is_provisioning

- import_tasks: _start_prometheus_operator.yml
  when: containers.prometheus_operator.is_provisioning

- import_tasks: _patch_kube_proxy.yml
  when: containers.prometheus_operator.is_provisioning
